### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by Blabla5943** [seanghay/nsfwjs-server#2]
Hello,

When I install and run the projet, I have this error:

```
2022-02-14 20:16:34.789753: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
```

Then, when I try to execute this command line into other terminal:
```
curl --request POST http://localhost:8080/ \
  --header 'Content-Type: multipart/form-data' \
  --data-binary 'image=@/images/a.png'
```
OR
`curl -F "image=@/images/a.png" "http://localhost:8080/"`
I have this error into the console:
```
Error: Multipart: Boundary not found
    at new Multipart (/usr/src/app/node_modules/busboy/lib/types/multipart.js:58:11)
    at Multipart (/usr/src/app/node_modules/busboy/lib/types/multipart.js:26:12)
    at Busboy.parseHeaders (/usr/src/app/node_modules/busboy/lib/main.js:71:22)
    at new Busboy (/usr/src/app/node_modules/busboy/lib/main.js:22:10)
    at multerMiddleware (/usr/src/app/node_modules/multer/lib/make-middleware.js:33:16)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:281:22
```

Why? How can I fix this?

Thank you!

**Comment by AireWong** [comment]
I have the same problem too.

**Comment by seanghay** [comment]
@AireWong 

The doc is misleading. I've updated it now. Sorry for that.

```
curl --request POST http://localhost:8080/ \
  --header 'Content-Type: multipart/form-data' \
  --form 'file=@image.jpg'
```
